- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    pool_dir: "/var/lib/libvirt/images"
    vm_k8s_role:
      worker: "worker"
      controlplane: "controlplane"
    id: "03"
    vm: "{{ vm_k8s_role.worker }}-{{ id }}-f38"
    vcpus: 2
    ram_mb: 2048
    cleanup: no
    net: "{{ br_name }}"
    mac_addr: "{{ vm_mac_addr_prefix }}:{{ id }}"
    ip_addr: "{{ br_net_addr_prefix }}.{{ id }}"
    root_pass: "test"
    ssh_pub_key: "/home/pdorau/.ssh/id_rsa.pub"

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm
      vars:
        libvirt_image_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        vm_mac_addr: "{{ mac_addr }}"
        vm_ip_addr: "{{ ip_addr }}"
        vm_root_pass: "{{ root_pass }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"
