- name: Create VM (not existing)
  block:

  - name: Download base image
    get_url:
      url: "{{ base_image_url }}"
      dest: "/tmp/{{ base_image_name }}"
      checksum: "sha256:{{ base_image_sha }}"

  - name: Copy base image to libvirt directory
    copy:
      dest: "{{ libvirt_image_dir }}/{{ vm_name }}.qcow2"
      src: "/tmp/{{ base_image_name }}"
      force: no
      remote_src: yes 
      mode: 0660
    register: copy_results

  - name: Configure the image
    command: |
      virt-customize -v -a {{ libvirt_image_dir }}/{{ vm_name }}.qcow2 \
      --hostname {{ vm_name }} \
      --root-password password:{{ vm_root_pass }} \
      --ssh-inject 'root:file:{{ ssh_key }}' \
      --uninstall cloud-init \
      --selinux-relabel
    when: copy_results is changed
  - name: Define vm
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('template', 'worker-vm.xml.j2') }}"
  when: "vm_name not in existing_vms.list_vms"

- name: Add VM to net bridge DHCP pool
  community.libvirt.virt_net:
    name: "{{ br_name }}"
    command: modify
    xml: "<host mac='{{ vm_mac_addr }}' name='{{ vm_name }}' ip='{{ vm_ip_addr }}'/>"